# Generated by Django 6.0 on 2025-12-06 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_json', models.FileField(blank=True, null=True, upload_to='restaurant_menus/json/')),
                ('menu_extract_status', models.CharField(choices=[('idle', 'Idle'), ('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='idle', max_length=12)),
                ('menu_last_extracted_at', models.DateTimeField(blank=True, null=True)),
                ('menu_extract_error', models.TextField(blank=True, default='', help_text='Error message if extraction fails')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantMenuImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant_menus/images/')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Image ordering (e.g., page number)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_images', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
