# Generated by Django 6.0 on 2025-12-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurantmenupdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pos_menu_last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When we last pulled menu JSON from external POS.', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pos_menu_raw',
            field=models.JSONField(blank=True, help_text='Latest raw menu JSON as received from external POS (full categories + items dump).', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pos_source',
            field=models.CharField(blank=True, help_text="External system source, e.g. 'yopos', 'petpooja', etc.", max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pos_store_id',
            field=models.CharField(blank=True, help_text='External store id / code from POS system.', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_json',
            field=models.FileField(blank=True, help_text='LLM-based extracted menu JSON file (from images/PDFs).', null=True, upload_to='restaurant_menus/json/'),
        ),
    ]
