# Generated by Django 6.0 on 2025-12-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_menuimportjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='pos_menu_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='pos_menu_raw',
            field=models.JSONField(blank=True, help_text='Latest raw menu JSON as received from external POS (full dump).', null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='pos_source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='pos_store_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantmenuimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
