# Generated by Django 6.0 on 2025-12-06 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.CharField(db_index=True, help_text='Public token for iframe embed URL.', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_domains', models.TextField(blank=True, help_text='Optional: comma-separated list of allowed domains for embedding.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='widget', to='restaurants.restaurant')),
            ],
        ),
    ]
