# Generated by Django 6.0 on 2025-12-06 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('normalized_name', models.CharField(blank=True, db_index=True, help_text='Lowercased, cleaned name for matching.', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='INR', max_length=3)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, help_text='False = old/inactive, not shown in current menu.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['restaurant', 'name'],
                'indexes': [models.Index(fields=['restaurant', 'is_active', 'available'], name='menu_menuit_restaur_cf23e0_idx'), models.Index(fields=['restaurant', 'normalized_name'], name='menu_menuit_restaur_9fb1b4_idx')],
            },
        ),
    ]
