# Generated by Django 6.0 on 2025-12-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of ingredients, if provided.', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='False means archived (not part of current menu sync).'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='external_item_id',
            field=models.CharField(blank=True, db_index=True, help_text='External POS item id (e.g., from Yopos).', max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='Full original item JSON from POS / extractor.', null=True),
        ),
    ]
