# Generated by Django 6.0 on 2025-12-10 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_ingredients_menuitem_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, help_text='Lowercased, cleaned name for matching.', max_length=255),
        ),
    ]
