# Generated by Django 6.0 on 2025-12-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menuitem_options_alter_menuitem_ingredients_and_more'),
        ('restaurants', '0004_menuimportjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='external_category_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='External POS category id (if available).', max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='external_item_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='External POS item id (if available).', max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitemimage',
            name='external_attachment_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='menusection',
            name='external_menu_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='External POS section/menu id (if available).', max_length=50),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['restaurant', 'is_active'], name='menu_catego_restaur_c97a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='menusection',
            index=models.Index(fields=['restaurant', 'is_active'], name='menu_menuse_restaur_99fd6f_idx'),
        ),
    ]
