# Generated by Django 6.0 on 2025-12-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_category_external_category_id_and_more'),
        ('restaurants', '0005_alter_restaurant_pos_menu_last_synced_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='uniq_category_per_restaurant_external_id',
        ),
        migrations.AlterField(
            model_name='category',
            name='external_category_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('external_category_id', ''), _negated=True), fields=('restaurant', 'external_category_id'), name='uniq_category_per_restaurant_external_id'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('external_category_id', '')), fields=('restaurant', 'slug'), name='uniq_category_per_restaurant_slug_when_no_external'),
        ),
    ]
